services:
  mysql:
    image: mysql:latest
    container_name: hospital-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: OrangeFinal
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
    ports:
      - "3307:3306"  # Ensure it's properly formatted as a list
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: hospital-app
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: 12345
      DB_NAME: OrangeFinal
      MYSQL_ROOT_PASSWORD: 12345
    command: ["python", "main.py"]
    

volumes:
  mysql_data: