name: Run Python Tests

on: [push, pull_request]  # Run tests on every push & pull request

jobs:
  test:
    runs-on: ubuntu-latest  # Use Ubuntu as the OS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Fetches the repo code

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # You can change this if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install project dependencies

      - name: Run tests with pytest
        run: pytest TestFinalProject.py  # Runs your test file
